# 3. More on Linear Algebra

**Instructions:**
* go through the notebook and complete the **tasks** .  
* Make sure you understand the examples given!
* When a question allows a free-form answer (e.g., ``what do you observe?``) create a new markdown cell below and answer the question in the notebook.
* ** Save your notebooks when you are done! **

See details on documentation / resources here:
https://learn.gold.ac.uk/mod/page/view.php?id=487982

<hr>
<span style="color:rgb(170,0,0)">**Task 1:**</span> Go through the tutorial on Linear Algebra in python here: http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html.

Paste and run the code from the tutorial in the empty cell below (or create new empty cells below) to get more familiar with the material.

In [4]:
import numpy as np
#Code here - use code samples from link above
a = np.array([
 [1,2,3],
 [4,5,6]
])
a.shape == (2,3)
b = np.array([
 [1,2,3]
])
b.shape == (1,3)

True

<span style="color:rgb(170,0,0)">**Task 2:**</span> Create the following matrices:
* $X=\begin{bmatrix} 2 & 3 & 4 \\ 1 & 2 &3 \end{bmatrix},Y=\begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 &0\\ 0 & 0 & 1 \end{bmatrix}$
* Multiply X with Y (Z1=X*Y=XY) and print the result.  What do you observe?
* Multiply X with Y transpose (Z2=X*Y.T) and print the result.  What do you observe?
* What can you tell about matrix Y, given Z1 and Z2?

In [16]:
#Code here
X = np.array([
    [2,3,4],
    [1,2,3],
    [0,0,0]
])

Y = np.array([
    [0,1,0],
    [1,0,0],
    [0,0,1]
])

print(X)
print(Y)

Z1 = X * Y
Z2 = X * Y.T

print(Z2)

[[2 3 4]
 [1 2 3]
 [0 0 0]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]
[[0 3 0]
 [1 0 0]
 [0 0 0]]


<span style="color:rgb(170,0,0)">**Task 3:**</span> Create a 2x2 identity matrix I using the numpy function ``eye(dim)`` 
$$ I=\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} $$

In [21]:
#Code here

i = np.eye(2, dtype=int)

print(i)

[[1 0]
 [0 1]]


<span style="color:rgb(170,0,0)">**Task 4:**</span> Multiply (using ``dot``) matrix I with the vector ``x`` defined below. Print the output.  What do you observe?
$$  =Ix$$

In [24]:
x=np.array([2,3])
print(x)
#Code here

y = np.dot(i,x)

print(y)

[2 3]
[2 3]


<span style="color:rgb(170,0,0)">**Task 5:**</span> Multiply (using ``dot``) matrix I with the matrix ``X`` defined below. Print the output.  What do you observe? 
$$=IX$$

In [25]:
X=np.array([[2,3],[4,5]])
print(x)
#Code here

y = np.dot(i, X)
print(y)

[2 3]
[[2 3]
 [4 5]]


<span style="color:rgb(170,0,0)">**Task 6:**</span> Multiply (using ``dot``) matrix $X$ with the inverse matrix, $X^{-1}$ (use the numpy function ``linalg.inv`` to do so).  What do you observe? $=$XX^{-1}$$


In [31]:
from numpy.linalg import inv
X=np.array([[1,2],[0,1]])
#Code here

Y = inv(X)

Z = np.dot(X, Y)

print(Z)

[[1. 0.]
 [0. 1.]]
