# 3. Introduction to numpy


**Instructions:**
* go through the notebook and complete the **tasks** .  
* Make sure you understand the examples given!
* ** Save your notebooks when you are done! **

Note that we use the import keyword to import modules and libraries in Python (more <a href="https://docs.python.org/3/tutorial/modules.html">here</a>)

See details on documentation / resources here:
https://learn.gold.ac.uk/mod/page/view.php?id=487982

In [3]:
import numpy as np

## 3.2 Numpy Arrays
Numpy ndarrays are a fundamental structure for ML in python.


### 3.2.1 Usage Examples

** Create numpy array from list **

    data1D = [6, 7, 8]
    data1DnD = np.array(data1D)
    print(data1D)
    print(data1DnD)
   

** print useful properties of our array **

    print(data1DnD.shape)
    print(data1DnD.ndim)
    print(data1DnD.dtype)
    
    
** change type of elements **

    data1DnD_float = data1DnD.astype(np.float)
    data1DnD_string = data1DnD.astype(np.string_)
   
    
** array indexing **

    print(a[0])   #return the first element of ndarray a
    print(a[:])   #return all the elements of ndarray a
    print(a[-1])  #return the last element of ndarray a
    print(a[:-1]) #return everything up to the last element
    print(a[:-2]) #return everything up to the second last element
    print(a[-2])  #return the second last element

** various ways of creating an ndarray **

    a = np.array([1, 2, 3])
    b = np.zeros((1,5))              # Create an array of all zeros
    c = np.ones((1,5))               # Create an array of all ones
    d = np.full((1,5), 7)            # Create an array filled with value 7
    e = np.random.random((1,4))      # Create an array filled with random values
    f = np.eye(3)                    # Create a 3x3 identity matrix (2D array)
    g = np.ones((3,3,3))             # 3-Dimensional array
    
** generalization to n-dimensional arrays **

    A=np.array([ [1,2], [3,4] ])     # Create a 2-D array (Matrix)
    print(A[0,1])                    # return the element on first column, second row (0,1)=2
                                     # array indexing works as above
    

** reshaping **

    We can reshape a vector (e.g., v=[v1,v2,...vN]) to a matrix of N1, N2 dimensions (where N1xN2 = N)
    This is very useful for plotting images.  For 2 dimensions, the related numpy method is np.reshape(ndarray, [dim1, dim2])
<hr>

<span style="color:rgb(170,0,0)">**Task:**</span>
- Go through the examples above, pasting the code given in the empty cell below and verifying the results.  
- Make sure you understand what this basic code does (numpy documentation <a href="http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html">here</a>)

In [6]:
#Code here

data1D = [6, 7, 8]
data1DnD = np.array(data1D)
print(data1D)
print(data1DnD)

print(data1DnD.shape)
print(data1DnD.ndim)
print(data1DnD.dtype)

data1DnD_float = data1DnD.astype(np.float)
data1DnD_string = data1DnD.astype(np.string_)


a = np.array([1, 2, 3])
b = np.zeros((1,5))              # Create an array of all zeros
c = np.ones((1,5))               # Create an array of all ones
d = np.full((1,5), 7)            # Create an array filled with value 7
e = np.random.random((1,4))      # Create an array filled with random values
f = np.eye(3)                    # Create a 3x3 identity matrix (2D array)
g = np.ones((3,3,3))             # 3-Dimensional array

print(a[0])   #return the first element of ndarray a
print(a[:])   #return all the elements of ndarray a
print(a[-1])  #return the last element of ndarray a
print(a[:-1]) #return everything up to the last element
print(a[:-2]) #return everything up to the second last element
print(a[-2])  #return the second last element


A=np.array([ [1,2], [3,4] ])     # Create a 2-D array (Matrix)
print(A[0,1])                    # return the element on first column, second row (0,1)=2
                                 # array indexing works as above

[6, 7, 8]
[6 7 8]
(3,)
1
int64
1
[1 2 3]
3
[1 2]
[1]
2
2


<span style="color:rgb(170,0,0)">**Task:**</span> In the empty cell below,  create an np array called L consisting of 15 random elements

In [8]:
#Code here

list = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
L = np.array(list)

print(L)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


<span style="color:rgb(170,0,0)">**Task:**</span> Reshape the array L to a matrix A that has 5 rows and 3 columns.  Print the matrix to verify the result.

In [9]:
#Code here

np.reshape(L, [5, 3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

<span style="color:rgb(170,0,0)">**Task:**</span> Reshape matrix A to a matrix B that has 3 rows and 5 columns.  Then, print the elements in row 0 and 1 only.

In [15]:
#Code here

a = np.reshape(L, [3, 5])
print(a)
print(a[0])
print(a[1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4]
[5 6 7 8 9]


<span style="color:rgb(170,0,0)">**Task:**</span> Print all elements of B that are in row 0 and 2 **and** column 1

In [16]:
#Code here

print(a[0][1])
print(a[2][1])

1
11


<span style="color:rgb(170,0,0)">**Task:**</span> Print all elements of A that are in the last row (see the [-1] notation above) and second to last column.  

In [17]:
#Code here

print(a[-1])

[10 11 12 13 14]


<span style="color:rgb(170,0,0)">**Task:**</span> Given the array Y below, find all **indices** in the array that are equal to the value 1.  Use the numpy function ``where`` to do that . Your final output should look like this: ``[1, 3, 4, 7]``.

documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.where.html

In [19]:
Y=np.array([0, 1, 0, 1,1, 2,0,1,0])
#Code here

np.where(Y == 1)

(array([1, 3, 4, 7]),)

<span style="color:rgb(170,0,0)">**Task:**</span> Split the array Y defined above into three arrays by using the numpy function ``array_split``.  Print to verify.

Documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.array_split.html. 

In [20]:
#Code here

np.array_split(Y, 3)

[array([0, 1, 0]), array([1, 1, 2]), array([0, 1, 0])]

<span style="color:rgb(170,0,0)">**Task:**</span> Given the array D defined below, find the **indices** that sort the array.  Use the numpy function ``argsort`` in order to do so.  Subsequently, print the sorted array.  Final output should look like this:
``
[ 0  1  2  5  9 10 20]
``

In [31]:
D=np.array([10,5,2,9,20,0,1])
#Code here

np.sort(D)


array([ 0,  1,  2,  5,  9, 10, 20])

<span style="color:rgb(170,0,0)">**Task:**</span> Create two random 2x2 matrices X and Y (2 rows, 2 columns).  Use the numpy function ``concatenate`` in order to concatenate them and create a matrix Z that has dimensions 4x2 and a matrix W that has dimensions 2x4

documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html

In [47]:
#Code here

x = np.array([0,1,0,1])
y = np.array([0,2,0,2])


temp = np.concatenate((x, y))

Z = np.reshape(temp, [4, 2])
W = np.reshape(temp, [2, 4])
print(Z)
print("----")
print(W)

[[0 1]
 [0 1]
 [0 2]
 [0 2]]
----
[[0 1 0 1]
 [0 2 0 2]]


<span style="color:rgb(170,0,0)">**Task:**</span> Create the same matrices Z2=Z and W2=W (where Z and W are as defined above), but this time use the numpy functions ``hstack`` and ``vstack``

Documentation:

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.hstack.html#numpy.hstack

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vstack.html#numpy.vstack

In [ ]:
#Code here



